version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      - /gatsby-starter-netify-cms/node_modules
      - .:/gatsby-starter-netlify-cms
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
